# Generated by Django 5.2.7 on 2026-06-20 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibleHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.CharField(choices=[('AGAKHAN', 'Agakhan'), ('AFRICA', 'Africa'), ('KAKUNGULU', 'Kakungulu'), ('LUWANGULA', 'Luwangula')], max_length=50)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligible_houses', to='posts.post')),
            ],
            options={
                'verbose_name': 'Eligible House',
                'verbose_name_plural': 'Eligible Houses',
                'unique_together': {('post', 'house')},
            },
        ),
    ]
