# Generated by Django 5.2.7 on 2026-06-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_election_alter_post_title_post_election_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='required_selections',
            field=models.PositiveIntegerField(default=1, help_text='Number of candidates that must be selected for this position.'),
        ),
    ]
