# Generated by Django 5.2.7 on 2026-06-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_rename_student_name_voter_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='has_voted',
        ),
        migrations.AlterField(
            model_name='voter',
            name='house',
            field=models.CharField(choices=[('AGAKHAN', 'Agakhan'), ('AFRICA', 'Africa'), ('KAKUNGULU', 'Kakungulu'), ('LUWANGULA', 'Luwangula')], max_length=50),
        ),
    ]
