# Generated by Django 5.2.7 on 2026-06-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_rename_name_voter_full_name_remove_voter_has_voted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='pin_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
