# Generated by Django 5.2.7 on 2026-06-20 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_voter_pin_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='pin_hash',
            new_name='pin',
        ),
    ]
