# Generated by Django 5.2.7 on 2026-06-24 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
        ('posts', '0004_post_required_selections'),
        ('voting', '0005_rename_pin_hash_to_pin'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('voter', 'post', 'candidate')},
        ),
    ]
