# Generated by Django 5.2.7 on 2026-06-24 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_alter_vote_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='pin',
        ),
    ]
