# Generated by Django 5.2.7 on 2026-06-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_remove_voter_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='pin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
