# Generated by Django 5.2.7 on 2025-10-25 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('_class', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, upload_to='candidates/photos/')),
                ('stream', models.CharField(blank=True, max_length=50)),
                ('slogan', models.TextField(blank=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='posts.post')),
            ],
        ),
    ]
